### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by wuge1880** [Omergral/Semantify#2]
Hi, thank you for sharing this fantastic work.  Could you please tell me where to find the "mean.npy" and "vt.npy" files? It seems like they are not included in the Flame dataset.

**Comment by Omergral** [comment]
Hey!

Thanks for commenting.

Actually, the files are stored under the "Flame Texture Space" (see attached images).
Please download it as well, then when you open it you will see the files you are referring to.

![image](https://github.com/Omergral/Semantify/assets/75261279/93195d16-260a-4551-b0da-bc6c2d9b4129)
![image](https://github.com/Omergral/Semantify/assets/75261279/0e561865-149c-45c6-b0f5-636aa1bd81f3)

**Comment by wuge1880** [comment]
Many thanks for the tip. I've already located the files.
