### ISSUE TITLE
.npy files not available on the given link

### ISSUE THREAD

**Issue by mondalanindya** [Omergral/Semantify#3]
![image](https://github.com/Omergral/Semantify/assets/42895181/b4c8925d-aa9f-4af9-bd1e-673265886d5f)
I downloaded the TextureSpace.zip from the website, but it only has the npz and the PDF files, not the other .npy files inside it.

**Comment by Omergral** [comment]
Correct.
Open the .npz and there you will find the files

**Comment by mondalanindya** [comment]
Can you suggest how to "open" the npz file?

**Comment by Omergral** [comment]
I use my MacBook's default archive utility 

![image](https://github.com/Omergral/Semantify/assets/75261279/a5fbe315-7917-4db8-ab8f-416278fb66cc)
